# Generated by Django 6.0.1 on 2026-01-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(related_name='participants', to='events.event'),
        ),
    ]
