# Generated by Django 6.0.1 on 2026-01-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rsvp_event_participants_delete_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imagelink',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
