# Generated by Django 6.0.1 on 2026-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imagelink',
            field=models.ImageField(blank=True, default='https://picsum.photos/seed/picsum/500/300', null=True, upload_to='event_images/'),
        ),
    ]
