# Generated by Django 6.0.1 on 2026-01-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imagelink',
            field=models.ImageField(blank=True, default='/event_images/default.jpg', null=True, upload_to='event_images/'),
        ),
    ]
